import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { Download, CheckCircle2, DollarSign } from "lucide-react";

import { invoicesService } from "@/services/wape.service";
import type { Invoice } from "@/types/api";

import PageHeader from "@/components/shared/PageHeader";
import DataTable from "@/components/shared/DataTable";
import StatusBadge from "@/components/shared/StatusBadge";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmt(amount?: number, currency = "MAD") {
  if (amount == null) return "—";
  return `${amount.toLocaleString()} ${currency}`;
}

// ── Component ─────────────────────────────────────────────────────────────────

export default function InvoicesPage() {
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  const queryClient = useQueryClient();

  // ── Queries
  const { data: invoicesData, isLoading } = useQuery({
    queryKey: ["invoices"],
    queryFn: () => invoicesService.list({ limit: 100 }),
  });

  const invoices = (invoicesData?.items ?? []) as Invoice[];

  // ── Mutations
  const validateMutation = useMutation({
    mutationFn: (id: string) => invoicesService.validate(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["invoices"] }),
  });

  const markPaidMutation = useMutation({
    mutationFn: (id: string) => invoicesService.markPaid(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["invoices"] }),
  });

  // ── PDF Export (client-side)
  const exportPDF = async (inv: Invoice) => {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();
    doc.setFontSize(20);
    doc.setTextColor(30, 64, 175);
    doc.text("INVOICE", 20, 20);
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);
    doc.text(`Invoice #: ${inv.invoiceNumber ?? inv.id?.slice(-8)}`, 20, 35);
    doc.text(
      `Date: ${inv.createdAt ? format(new Date(inv.createdAt), "MMM d, yyyy") : "—"}`,
      20,
      45,
    );
    doc.text(`Status: ${inv.status ?? "—"}`, 20, 55);
    doc.text(`Amount: ${fmt(inv.amount, inv.currency)}`, 20, 65);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 72, 190, 72);
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text("Generated by WAPE", 20, 82);
    doc.save(`invoice_${inv.invoiceNumber ?? inv.id?.slice(-8)}.pdf`);
  };

  // ── Stats
  const totalAmount = invoices.reduce((s, inv) => s + (inv.amount ?? 0), 0);
  const paidCount = invoices.filter((inv) => inv.status === "paid").length;
  const pendingCount = invoices.filter(
    (inv) => inv.status === "pending_validation" || inv.status === "validated",
  ).length;

  // ── Filtering
  const filtered = invoices.filter((inv) => {
    const matchSearch =
      !search ||
      inv.invoiceNumber?.toLowerCase().includes(search.toLowerCase()) ||
      inv.recipient?.toLowerCase().includes(search.toLowerCase());
    const matchStatus = statusFilter === "all" || inv.status === statusFilter;
    return matchSearch && matchStatus;
  });

  // ── Columns
  const columns = [
    {
      header: "Invoice #",
      cell: (row: Invoice) => (
        <div>
          <p className="font-medium font-mono text-xs">
            {row.invoiceNumber ?? row.id?.slice(-8)}
          </p>
          <Badge variant="outline" className="text-xs mt-0.5">
            {row.type ?? "—"}
          </Badge>
        </div>
      ),
    },
    {
      header: "Recipient",
      cell: (row: Invoice) => (
        <span className="text-sm">{row.recipient ?? "—"}</span>
      ),
    },
    {
      header: "Amount",
      cell: (row: Invoice) => (
        <span className="font-semibold">{fmt(row.amount, row.currency)}</span>
      ),
    },
    {
      header: "Date",
      cell: (row: Invoice) =>
        row.createdAt ? format(new Date(row.createdAt), "MMM d, yyyy") : "—",
    },
    {
      header: "Status",
      cell: (row: Invoice) => <StatusBadge status={row.status ?? "draft"} />,
    },
    {
      header: "PDF",
      cell: (row: Invoice) =>
        row.pdfUrl ? (
          <a href={row.pdfUrl} target="_blank" rel="noopener noreferrer">
            <Button variant="ghost" size="icon" className="h-8 w-8">
              <Download className="w-4 h-4" />
            </Button>
          </a>
        ) : (
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => exportPDF(row)}
          >
            <Download className="w-4 h-4" />
          </Button>
        ),
    },
    {
      header: "",
      cell: (row: Invoice) => (
        <div className="flex gap-1">
          {row.status === "pending_validation" && (
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs gap-1 text-primary border-primary/30"
              onClick={() => validateMutation.mutate(row.id)}
              disabled={validateMutation.isPending}
            >
              <CheckCircle2 className="w-3 h-3" /> Validate
            </Button>
          )}
          {row.status === "validated" && (
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs gap-1 text-success border-success/30"
              onClick={() => markPaidMutation.mutate(row.id)}
              disabled={markPaidMutation.isPending}
            >
              <DollarSign className="w-3 h-3" /> Mark Paid
            </Button>
          )}
          {row.status === "paid" && (
            <Badge
              variant="outline"
              className="text-xs bg-success/10 text-success border-success/20"
            >
              Paid
            </Badge>
          )}
        </div>
      ),
    },
  ];

  // ── Render
  return (
    <div className="space-y-4">
      {/* Summary */}
      <div className="grid grid-cols-3 gap-4">
        {[
          {
            label: "Total Invoiced",
            value: fmt(totalAmount),
            color: "text-primary bg-primary/10",
          },
          {
            label: "Paid",
            value: paidCount,
            color: "text-success bg-success/10",
          },
          {
            label: "Pending",
            value: pendingCount,
            color: "text-warning bg-warning/10",
          },
        ].map(({ label, value, color }) => (
          <div
            key={label}
            className="flex items-center gap-3 p-4 rounded-lg border border-border bg-card"
          >
            <div className={`p-2 rounded-lg ${color}`}>
              <DollarSign className="w-4 h-4" />
            </div>
            <div>
              <p className="text-xs text-muted-foreground">{label}</p>
              <p className="text-lg font-bold">{value}</p>
            </div>
          </div>
        ))}
      </div>

      <PageHeader
        title="Invoices"
        subtitle={`${invoices.length} invoices — auto-generated from confirmed attachments`}
        searchValue={search}
        onSearch={setSearch}
      >
        <Select value={statusFilter} onValueChange={setStatusFilter}>
          <SelectTrigger className="w-44 bg-card">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Status</SelectItem>
            <SelectItem value="pending_validation">
              Pending Validation
            </SelectItem>
            <SelectItem value="validated">Validated</SelectItem>
            <SelectItem value="paid">Paid</SelectItem>
          </SelectContent>
        </Select>
      </PageHeader>

      <DataTable columns={columns} data={filtered} isLoading={isLoading} />
    </div>
  );
}
