import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { format } from "date-fns";
import { Download, CheckCircle2, DollarSign } from "lucide-react";
import { invoicesService } from "@/services/wape.service";
import PageHeader from "@/components/shared/PageHeader";
import DataTable from "@/components/shared/DataTable";
import StatusBadge from "@/components/shared/StatusBadge";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue, } from "@/components/ui/select";
// ── Helpers ───────────────────────────────────────────────────────────────────
function fmt(amount, currency = "MAD") {
    if (amount == null)
        return "—";
    return `${amount.toLocaleString()} ${currency}`;
}
// ── Component ─────────────────────────────────────────────────────────────────
export default function InvoicesPage() {
    const [search, setSearch] = useState("");
    const [statusFilter, setStatusFilter] = useState("all");
    const queryClient = useQueryClient();
    // ── Queries
    const { data: invoicesData, isLoading } = useQuery({
        queryKey: ["invoices"],
        queryFn: () => invoicesService.list({ limit: 100 }),
    });
    const invoices = (invoicesData?.items ?? []);
    // ── Mutations
    const validateMutation = useMutation({
        mutationFn: (id) => invoicesService.validate(id),
        onSuccess: () => queryClient.invalidateQueries({ queryKey: ["invoices"] }),
    });
    const markPaidMutation = useMutation({
        mutationFn: (id) => invoicesService.markPaid(id),
        onSuccess: () => queryClient.invalidateQueries({ queryKey: ["invoices"] }),
    });
    // ── PDF Export (client-side)
    const exportPDF = async (inv) => {
        const { jsPDF } = await import("jspdf");
        const doc = new jsPDF();
        doc.setFontSize(20);
        doc.setTextColor(30, 64, 175);
        doc.text("INVOICE", 20, 20);
        doc.setFontSize(11);
        doc.setTextColor(0, 0, 0);
        doc.text(`Invoice #: ${inv.invoiceNumber ?? inv.id?.slice(-8)}`, 20, 35);
        doc.text(`Date: ${inv.createdAt ? format(new Date(inv.createdAt), "MMM d, yyyy") : "—"}`, 20, 45);
        doc.text(`Status: ${inv.status ?? "—"}`, 20, 55);
        doc.text(`Amount: ${fmt(inv.amount, inv.currency)}`, 20, 65);
        doc.setDrawColor(200, 200, 200);
        doc.line(20, 72, 190, 72);
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("Generated by WAPE", 20, 82);
        doc.save(`invoice_${inv.invoiceNumber ?? inv.id?.slice(-8)}.pdf`);
    };
    // ── Stats
    const totalAmount = invoices.reduce((s, inv) => s + (inv.amount ?? 0), 0);
    const paidCount = invoices.filter((inv) => inv.status === "paid").length;
    const pendingCount = invoices.filter((inv) => inv.status === "pending_validation" || inv.status === "validated").length;
    // ── Filtering
    const filtered = invoices.filter((inv) => {
        const matchSearch = !search ||
            inv.invoiceNumber?.toLowerCase().includes(search.toLowerCase()) ||
            inv.recipient?.toLowerCase().includes(search.toLowerCase());
        const matchStatus = statusFilter === "all" || inv.status === statusFilter;
        return matchSearch && matchStatus;
    });
    // ── Columns
    const columns = [
        {
            header: "Invoice #",
            cell: (row) => (_jsxs("div", { children: [_jsx("p", { className: "font-medium font-mono text-xs", children: row.invoiceNumber ?? row.id?.slice(-8) }), _jsx(Badge, { variant: "outline", className: "text-xs mt-0.5", children: row.type ?? "—" })] })),
        },
        {
            header: "Recipient",
            cell: (row) => (_jsx("span", { className: "text-sm", children: row.recipient ?? "—" })),
        },
        {
            header: "Amount",
            cell: (row) => (_jsx("span", { className: "font-semibold", children: fmt(row.amount, row.currency) })),
        },
        {
            header: "Date",
            cell: (row) => row.createdAt ? format(new Date(row.createdAt), "MMM d, yyyy") : "—",
        },
        {
            header: "Status",
            cell: (row) => _jsx(StatusBadge, { status: row.status ?? "draft" }),
        },
        {
            header: "PDF",
            cell: (row) => row.pdfUrl ? (_jsx("a", { href: row.pdfUrl, target: "_blank", rel: "noopener noreferrer", children: _jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", children: _jsx(Download, { className: "w-4 h-4" }) }) })) : (_jsx(Button, { variant: "ghost", size: "icon", className: "h-8 w-8", onClick: () => exportPDF(row), children: _jsx(Download, { className: "w-4 h-4" }) })),
        },
        {
            header: "",
            cell: (row) => (_jsxs("div", { className: "flex gap-1", children: [row.status === "pending_validation" && (_jsxs(Button, { size: "sm", variant: "outline", className: "h-7 text-xs gap-1 text-primary border-primary/30", onClick: () => validateMutation.mutate(row.id), disabled: validateMutation.isPending, children: [_jsx(CheckCircle2, { className: "w-3 h-3" }), " Validate"] })), row.status === "validated" && (_jsxs(Button, { size: "sm", variant: "outline", className: "h-7 text-xs gap-1 text-success border-success/30", onClick: () => markPaidMutation.mutate(row.id), disabled: markPaidMutation.isPending, children: [_jsx(DollarSign, { className: "w-3 h-3" }), " Mark Paid"] })), row.status === "paid" && (_jsx(Badge, { variant: "outline", className: "text-xs bg-success/10 text-success border-success/20", children: "Paid" }))] })),
        },
    ];
    // ── Render
    return (_jsxs("div", { className: "space-y-4", children: [_jsx("div", { className: "grid grid-cols-3 gap-4", children: [
                    {
                        label: "Total Invoiced",
                        value: fmt(totalAmount),
                        color: "text-primary bg-primary/10",
                    },
                    {
                        label: "Paid",
                        value: paidCount,
                        color: "text-success bg-success/10",
                    },
                    {
                        label: "Pending",
                        value: pendingCount,
                        color: "text-warning bg-warning/10",
                    },
                ].map(({ label, value, color }) => (_jsxs("div", { className: "flex items-center gap-3 p-4 rounded-lg border border-border bg-card", children: [_jsx("div", { className: `p-2 rounded-lg ${color}`, children: _jsx(DollarSign, { className: "w-4 h-4" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-xs text-muted-foreground", children: label }), _jsx("p", { className: "text-lg font-bold", children: value })] })] }, label))) }), _jsx(PageHeader, { title: "Invoices", subtitle: `${invoices.length} invoices — auto-generated from confirmed attachments`, searchValue: search, onSearch: setSearch, children: _jsxs(Select, { value: statusFilter, onValueChange: setStatusFilter, children: [_jsx(SelectTrigger, { className: "w-44 bg-card", children: _jsx(SelectValue, {}) }), _jsxs(SelectContent, { children: [_jsx(SelectItem, { value: "all", children: "All Status" }), _jsx(SelectItem, { value: "pending_validation", children: "Pending Validation" }), _jsx(SelectItem, { value: "validated", children: "Validated" }), _jsx(SelectItem, { value: "paid", children: "Paid" })] })] }) }), _jsx(DataTable, { columns: columns, data: filtered, isLoading: isLoading })] }));
}
